# Generated by Django 6.1 on 2026-08-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('retail', 'Retail / Shop'), ('wholesale', 'Wholesale / Distribution'), ('manufacturing', 'Manufacturing'), ('restaurant', 'Restaurant / Food'), ('services', 'Services'), ('other', 'Other')], default='retail', max_length=20)),
                ('currency', models.CharField(default='MWK', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
