# Generated by Django 5.2.15 on 2026-08-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_size',
            field=models.CharField(choices=[('micro', 'Micro (1–5 employees)'), ('small', 'Small (6–30 employees)'), ('medium', 'Medium (31–100+ employees)')], default='micro', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='organization',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail / Shop'), ('wholesale', 'Wholesale / Distribution'), ('manufacturing', 'Manufacturing'), ('restaurant', 'Restaurant / Food'), ('services', 'Services'), ('agriculture', 'Agriculture'), ('other', 'Other')], default='retail', max_length=20),
        ),
    ]
