# Generated by Django 5.2.15 on 2026-08-18 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_default_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_sales_summary', models.BooleanField(default=True)),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('out_of_stock_alert', models.BooleanField(default=True)),
                ('payment_overdue', models.BooleanField(default=True)),
                ('customer_payment_received', models.BooleanField(default=True)),
                ('new_login_alert', models.BooleanField(default=True)),
                ('password_changed_alert', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='Africa/Blantyre', max_length=100)),
                ('compact_mode', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
