# Generated by Django 5.2.15 on 2026-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notificationpreference_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Send notifications via email'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Send notifications via SMS'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Send notifications via WhatsApp'),
        ),
    ]
