# Generated by Django 5.2.15 on 2026-08-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_identitydocument_document_photo'),
        ('accounts', '0005_notificationpreference_email_enabled_and_more'),
    ]

    operations = [
    ]
