# Generated by Django 5.2.15 on 2026-08-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260820_1055'),
        ('accounts', '0006_userprofile_email_verified'),
    ]

    operations = [
    ]
