# Generated by Django 5.2.15 on 2026-08-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260820_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
        ),
    ]
