# Generated by Django 5.2.15 on 2026-08-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_product_cost_price_stockmovement_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Product category', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=50, null=True, unique=True),
        ),
    ]
