# Generated by Django 5.2.15 on 2026-08-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_product_cost_price_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='EAN-13, UPC, or internal barcode', max_length=100),
        ),
    ]
